// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq54O9Ek0K_nsR1aGIjTueg0KLZ57r2eE',
    appId: '1:482928107154:web:c0a74bd036f75f4c05d04b',
    messagingSenderId: '482928107154',
    projectId: 'chateapp-453b9',
    authDomain: 'chateapp-453b9.firebaseapp.com',
    storageBucket: 'chateapp-453b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlppT4Zny7zcbtHlhhmAoT99mg1vBHTF4',
    appId: '1:482928107154:android:afda20d44619810105d04b',
    messagingSenderId: '482928107154',
    projectId: 'chateapp-453b9',
    storageBucket: 'chateapp-453b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJlWJoIvBifWLwoGeNCcplJWxie2xkXzk',
    appId: '1:482928107154:ios:c64b084034fe9b7d05d04b',
    messagingSenderId: '482928107154',
    projectId: 'chateapp-453b9',
    storageBucket: 'chateapp-453b9.appspot.com',
    iosBundleId: 'com.example.chateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJlWJoIvBifWLwoGeNCcplJWxie2xkXzk',
    appId: '1:482928107154:ios:374559f8a681338b05d04b',
    messagingSenderId: '482928107154',
    projectId: 'chateapp-453b9',
    storageBucket: 'chateapp-453b9.appspot.com',
    iosBundleId: 'com.example.chateApp.RunnerTests',
  );
}
